[package]
name = "motor"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.5.1"
rusb = "0.9"
socketcan = "3.3.0"
deku = "0.18"
tungstenite = "*"
zenoh = "0.11.0"

serde = "1"
serde_json = "1.0"

[[bin]]
name = "lkm"